# ==========================
# Exercise 2 - Part 1
# ==========================

# Make a graph to analyse the distribution of answers over time.

import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
from pathlib import Path
from math import pi

DAY_ORDER = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

def plot_answers_per_day(ax, answers_per_day):
    """Plot answers per day as a time series bar chart."""
    ax.bar(answers_per_day["date_only"], answers_per_day["count"], width=0.8, color="#4C72B0", alpha=0.85)
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha="right")
    ax.set_title("Answers per Day")
    ax.set_xlabel("Date")
    ax.set_ylabel("Number of Answers")


def plot_answers_per_hour(ax, answers_per_hour):
    """Plot answers by hour of day as a bar chart."""
    ax.bar(answers_per_hour["hour"], answers_per_hour["count"], color="#DD8452", alpha=0.85)
    ax.set_xticks(range(0, 24))
    ax.set_title("Answers by Hour of Day (UTC)")
    ax.set_xlabel("Hour")
    ax.set_ylabel("Number of Answers")


def plot_answers_per_month(ax, answers_per_month):
    """Plot answers per month as a scatter plot."""
    ax.scatter(range(len(answers_per_month)), answers_per_month["count"], s=200, color="#9467BD", alpha=0.7, edgecolors="black", linewidth=1.5)
    ax.set_xticks(range(len(answers_per_month)))
    ax.set_xticklabels(answers_per_month["month"], rotation=45, ha="right")
    ax.set_title("Answers per Month")
    ax.set_xlabel("Month")
    ax.set_ylabel("Number of Answers")
    ax.grid(True, alpha=0.3)


def plot_answers_per_dayofweek(ax, answers_per_dayofweek):
    """Plot answers by day of week as a radar/Kiviat chart."""
    angles = [n / float(len(DAY_ORDER)) * 2 * pi for n in range(len(DAY_ORDER))]
    angles += angles[:1]  # Complete the circle
    values = answers_per_dayofweek["count"].tolist()
    values += values[:1]  # Complete the circle
    
    ax.plot(angles, values, 'o-', linewidth=2, color="#55A868")
    ax.fill(angles, values, alpha=0.35, color="#55A868")
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(DAY_ORDER)
    ax.set_ylim(0, max(values) * 1.1)
    ax.set_title("Answers by Day of Week (Kiviat)", pad=20)


def run_exercise_2(out_folder_path):
    # Read the parquet dataset generated by exercise 1
    df = pd.read_parquet(Path(out_folder_path) / "sample.parquet")

    # Aggregations: use pre-computed columns from exercise 1
    answers_per_day  = df.groupby("date_only").size().reset_index(name="count")
    answers_per_day["date_only"] = pd.to_datetime(answers_per_day["date_only"].astype(str))
    answers_per_hour = df.groupby("hour").size().reset_index(name="count")
    answers_per_month = df.groupby("month").size().reset_index(name="count")
    answers_per_dayofweek = (
        df.groupby("day_of_week")
          .size()
          .reindex(DAY_ORDER)
          .reset_index(name="count")
    )

    # Figure 
    fig = plt.figure(figsize=(16, 10))
    ax1 = fig.add_subplot(2, 2, 1)
    ax2 = fig.add_subplot(2, 2, 2)
    ax3 = fig.add_subplot(2, 2, 3)
    ax_radar = fig.add_subplot(2, 2, 4, projection='polar')
    fig.suptitle("Distribution of Answers Over Time", fontsize=16, fontweight="bold")

    # Create plots using dedicated functions
    plot_answers_per_day(ax1, answers_per_day)
    plot_answers_per_hour(ax2, answers_per_hour)
    plot_answers_per_month(ax3, answers_per_month)
    plot_answers_per_dayofweek(ax_radar, answers_per_dayofweek)

    plt.tight_layout()

    out_path = Path(out_folder_path) / "exercise_2_distribution.png"
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Graph saved to {out_path}")
